//
// Created by User on 11.02.2026.
//

#ifndef CLEANGRADUATOR_INFRASTRUCTUREMODULE_H
#define CLEANGRADUATOR_INFRASTRUCTUREMODULE_H

class InfrastructureModule {
};

#endif //CLEANGRADUATOR_INFRASTRUCTUREMODULE_H