#ifndef CLEANGRADUATOR_ANGLESOURCEFROMVIDEOCONFIG_H
#define CLEANGRADUATOR_ANGLESOURCEFROMVIDEOCONFIG_H

namespace infra::angle {
    struct AngleSourceFromVideoConfig {

    };
}

#endif //CLEANGRADUATOR_ANGLESOURCEFROMVIDEOCONFIG_H