#ifndef CLEANGRADUATOR_STAND4CALIBRATIONSTRATEGYCONFIG_H
#define CLEANGRADUATOR_STAND4CALIBRATIONSTRATEGYCONFIG_H

namespace infra::calib::stand4 {
    struct Stand4CalibrationStrategyConfig {

    };
}

#endif //CLEANGRADUATOR_STAND4CALIBRATIONSTRATEGYCONFIG_H